# Generated by Django 4.1.7 on 2023-02-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_userdata_user_account_postdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Anonymous', max_length=100)),
                ('Comment', models.TextField()),
                ('Time', models.DateTimeField(auto_now=True, null=True)),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postdata')),
            ],
        ),
    ]
