# Generated by Django 4.1.7 on 2023-02-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_commentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='Name',
        ),
    ]
