# Generated by Django 4.1.7 on 2023-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userdata_email_remove_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
